using Microsoft.EntityFrameworkCore.Migrations;
using ManufacturingCoordinator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace ManufacturingCoordinator.Api.Migrations
{
    /// <summary>
    /// Adds the catalogue hierarchy while retaining historical inventory and orders.
    /// Unmapped materials remain explicitly unassigned for manual reconciliation.
    /// </summary>
    [Migration("20260930160000_ResetInventoryCatalogue")]
    [DbContext(typeof(ApplicationDbContext))]
    public partial class ResetInventoryCatalogue : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PackagingTypes",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    ShortCode = table.Column<string>(type: "character varying(12)", maxLength: 12, nullable: false),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table => table.PrimaryKey("PK_PackagingTypes", x => x.Id));

            migrationBuilder.CreateIndex(name: "IX_PackagingTypes_Name", table: "PackagingTypes", column: "Name", unique: true);
            migrationBuilder.CreateIndex(name: "IX_PackagingTypes_ShortCode", table: "PackagingTypes", column: "ShortCode", unique: true);

            // The inventory tables were originally owned by a separate
            // context, so make the shared schema complete on both fresh and
            // existing development databases.
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "InventoryItems" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Sku" text NOT NULL,
                    "Name" text NOT NULL,
                    "Category" text NOT NULL,
                    "StockLevel" integer NOT NULL,
                    "ReorderThreshold" integer NOT NULL
                );
                CREATE TABLE IF NOT EXISTS "StockAlerts" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Sku" text NOT NULL,
                    "PackagingType" text NOT NULL,
                    "QuantityRequested" integer NOT NULL,
                    "Status" text NOT NULL,
                    "Timestamp" timestamp with time zone NOT NULL,
                    "WorkerId" text NOT NULL
                );
                CREATE TABLE IF NOT EXISTS "InventoryRolls" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "RawMaterialId" integer NOT NULL,
                    "BarcodeUrl" text NOT NULL,
                    "RollIdentifier" text NOT NULL,
                    "InitialQuantity" numeric NOT NULL,
                    "CurrentQuantity" numeric NOT NULL,
                    "Status" text NOT NULL,
                    "ReceivedDate" timestamp with time zone NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL
                );
                CREATE TABLE IF NOT EXISTS "StockLevels" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "RawMaterialId" integer NOT NULL,
                    "TotalQuantity" numeric NOT NULL,
                    "Notes" text NOT NULL,
                    "RecordedAt" timestamp with time zone NOT NULL
                );
                ALTER TABLE "InventoryItems" ADD COLUMN IF NOT EXISTS "PackagingTypeId" integer NULL;
                ALTER TABLE "InventoryItems" ADD COLUMN IF NOT EXISTS "RawMaterialId" integer NULL;
                ALTER TABLE "InventoryItems" ADD COLUMN IF NOT EXISTS "SkuNumber" integer NULL;
                ALTER TABLE "RawMaterials" ADD COLUMN IF NOT EXISTS "MaterialCode" character varying(20) NOT NULL DEFAULT '';
                ALTER TABLE "RawMaterials" ADD COLUMN IF NOT EXISTS "PackagingTypeId" integer NULL;
                """);

            // An inactive unassigned category is a reconciliation marker, not
            // an inferred packaging identity. Never delete historical records.
            migrationBuilder.Sql("""
                INSERT INTO "PackagingTypes" ("Id", "Name", "ShortCode", "IsActive")
                VALUES (-1, 'Unassigned historical catalogue', 'UNASSIGNED', false);
                UPDATE "RawMaterials" SET "PackagingTypeId" = -1 WHERE "PackagingTypeId" IS NULL;
                """);

            migrationBuilder.Sql("""
                ALTER TABLE "RawMaterials" ALTER COLUMN "PackagingTypeId" SET NOT NULL;
                ALTER TABLE "RawMaterials" ALTER COLUMN "MaterialCode" DROP DEFAULT;
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_InventoryItems_Sku" ON "InventoryItems" ("Sku");
                CREATE INDEX IF NOT EXISTS "IX_RawMaterials_PackagingTypeId_MaterialCode" ON "RawMaterials" ("PackagingTypeId", "MaterialCode");
                CREATE INDEX IF NOT EXISTS "IX_InventoryRolls_RollIdentifier" ON "InventoryRolls" ("RollIdentifier");
                ALTER TABLE "RawMaterials" ADD CONSTRAINT "FK_RawMaterials_PackagingTypes_PackagingTypeId"
                    FOREIGN KEY ("PackagingTypeId") REFERENCES "PackagingTypes" ("Id") ON DELETE RESTRICT;
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""ALTER TABLE "RawMaterials" DROP CONSTRAINT IF EXISTS "FK_RawMaterials_PackagingTypes_PackagingTypeId";""");
            migrationBuilder.DropTable(name: "PackagingTypes");
        }
    }
}
