using ManufacturingCoordinator.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace ManufacturingCoordinator.Api.Migrations;

// Replace the duplicate alignment experiment with additive shared-schema definitions.
[DbContext(typeof(ApplicationDbContext))]
[Migration("20261003170000_CompleteProcurementSchema")]
public class CompleteProcurementSchema : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder) => migrationBuilder.Sql("""
ALTER TABLE "PurchaseOrders" ADD COLUMN IF NOT EXISTS "ActualDeliveryDate" timestamp with time zone;
ALTER TABLE "PurchaseOrders" ADD COLUMN IF NOT EXISTS "BankReferenceNumber" character varying(100);
ALTER TABLE "PurchaseOrders" ADD COLUMN IF NOT EXISTS "BankSlipStatus" character varying(50);
ALTER TABLE "PurchaseOrders" ADD COLUMN IF NOT EXISTS "BankSlipUploadedAt" timestamp with time zone;
ALTER TABLE "PurchaseOrders" ADD COLUMN IF NOT EXISTS "BankSlipUrl" character varying(500);
ALTER TABLE "PurchaseOrders" ADD COLUMN IF NOT EXISTS "DeliveryRemarks" character varying(500);
ALTER TABLE "PurchaseOrders" ADD COLUMN IF NOT EXISTS "ExpectedDeliveryDate" timestamp with time zone;
ALTER TABLE "PurchaseOrders" ADD COLUMN IF NOT EXISTS "IsAcknowledgedByScm" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "PurchaseOrders" ADD COLUMN IF NOT EXISTS "IsFinancialVerified" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "PurchaseOrders" ADD COLUMN IF NOT EXISTS "IsQualityVerified" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "PurchaseOrders" ADD COLUMN IF NOT EXISTS "ProcurementRequestId" integer;
ALTER TABLE "PurchaseOrders" ADD COLUMN IF NOT EXISTS "TrackingNumber" character varying(200);
ALTER TABLE "PurchaseOrders" ADD COLUMN IF NOT EXISTS "TrackingStatus" character varying(50) NOT NULL DEFAULT 'Draft';
ALTER TABLE "AgentWorkflows" ADD COLUMN IF NOT EXISTS "ValidationResults" text NULL;
CREATE TABLE IF NOT EXISTS "ProcurementOutcomes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Material" character varying(200) NOT NULL,
    "RequestedQuantity" numeric(18,3) NOT NULL,
    "RecommendedQuantity" numeric(18,3) NOT NULL,
    "FinalOrderedQuantity" numeric(18,3) NOT NULL,
    "RecommendedSupplier" character varying(200) NOT NULL,
    "SelectedSupplier" character varying(200) NOT NULL,
    "EstimatedPrice" numeric(18,2) NOT NULL,
    "FinalPrice" numeric(18,2) NOT NULL,
    "EstimatedLeadTime" integer NOT NULL,
    "ActualLeadTime" integer NOT NULL,
    "QualityEvidence" character varying(1000) NOT NULL,
    "SupplierVerification" character varying(100) NOT NULL,
    "ManagerDecision" character varying(100) NOT NULL,
    "ManagerRevision" character varying(1000),
    "ProcurementSuccess" boolean NOT NULL,
    "PaymentSuccess" boolean NOT NULL,
    "DeliverySuccess" boolean NOT NULL,
    "QualityOutcome" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "CompletedAt" timestamp with time zone,
    "PurchaseOrderId" integer,
    "ProcurementRequestId" integer,
    CONSTRAINT "PK_ProcurementOutcomes" PRIMARY KEY ("Id")
);
CREATE TABLE IF NOT EXISTS "ProcurementRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RawMaterialId" integer NOT NULL,
    "RequiredSpecification" character varying(200) NOT NULL,
    "ProductionRequirement" numeric(18,3) NOT NULL,
    "CurrentStock" numeric(18,3) NOT NULL,
    "SafetyStock" numeric(18,3) NOT NULL,
    "ExistingOpenPoQuantity" numeric(18,3) NOT NULL,
    "CalculatedNetQuantity" numeric(18,3) NOT NULL,
    "MaximumBudget" numeric(18,2) NOT NULL,
    "RequiredByDate" timestamp with time zone NOT NULL,
    "QualityRequirement" character varying(500) NOT NULL,
    "PreferredRegion" character varying(100),
    "Status" text NOT NULL,
    "WorkflowId" character varying(100),
    "MaterialName" character varying(200),
    "RecommendedSupplierId" integer,
    "GeneratedPurchaseOrderId" integer,
    "FailureReason" character varying(1000),
    "CreatedById" uuid,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "Priority" character varying(50) NOT NULL,
    CONSTRAINT "PK_ProcurementRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProcurementRequests_PurchaseOrders_GeneratedPurchaseOrderId" FOREIGN KEY ("GeneratedPurchaseOrderId") REFERENCES "PurchaseOrders" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_ProcurementRequests_RawMaterials_RawMaterialId" FOREIGN KEY ("RawMaterialId") REFERENCES "RawMaterials" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ProcurementRequests_Suppliers_RecommendedSupplierId" FOREIGN KEY ("RecommendedSupplierId") REFERENCES "Suppliers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_ProcurementRequests_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS "SupplierCandidates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProcurementRequestId" integer NOT NULL,
    "SupplierId" integer,
    "SupplierName" character varying(200) NOT NULL,
    "MaterialName" character varying(200) NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "Currency" character varying(10) NOT NULL DEFAULT 'USD',
    "MinimumOrderQuantity" numeric(18,3) NOT NULL,
    "PackSize" numeric(18,3) NOT NULL DEFAULT 1.0,
    "LeadTimeDays" integer NOT NULL,
    "QualityEvidence" character varying(500) NOT NULL,
    "Availability" character varying(100) NOT NULL DEFAULT 'In Stock',
    "SupplierStatus" character varying(50) NOT NULL DEFAULT 'UNVERIFIED',
    "ConfidenceScore" numeric(5,2) NOT NULL,
    "SourceUrl" character varying(500),
    "IsValidated" boolean NOT NULL,
    "ValidationRemarks" character varying(1000),
    "RecommendedOrderQuantity" numeric(18,3) NOT NULL,
    "TotalCost" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_SupplierCandidates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SupplierCandidates_ProcurementRequests_ProcurementRequestId" FOREIGN KEY ("ProcurementRequestId") REFERENCES "ProcurementRequests" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SupplierCandidates_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE SET NULL
);
""");
    // Keep operational records during rollback; deployment must reconcile schema explicitly.
    protected override void Down(MigrationBuilder migrationBuilder) { }
}
