using Microsoft.EntityFrameworkCore.Migrations;
using ManufacturingCoordinator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace ManufacturingCoordinator.Api.Migrations
{
    /// <summary>
    /// Replaces the old free-text inventory catalogue with a packaging type /
    /// raw material / sequential SKU catalogue. This is deliberately a
    /// one-time data reset requested for the development database.
    /// </summary>
    [Migration("20260930160000_ResetInventoryCatalogue")]
    [DbContext(typeof(ApplicationDbContext))]
    public partial class ResetInventoryCatalogue : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PackagingTypes",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    ShortCode = table.Column<string>(type: "character varying(12)", maxLength: 12, nullable: false),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table => table.PrimaryKey("PK_PackagingTypes", x => x.Id));

            migrationBuilder.CreateIndex(name: "IX_PackagingTypes_Name", table: "PackagingTypes", column: "Name", unique: true);
            migrationBuilder.CreateIndex(name: "IX_PackagingTypes_ShortCode", table: "PackagingTypes", column: "ShortCode", unique: true);

            // The inventory tables were originally owned by a separate
            // context, so make the shared schema complete on both fresh and
            // existing development databases.
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "InventoryItems" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Sku" text NOT NULL,
                    "Name" text NOT NULL,
                    "Category" text NOT NULL,
                    "StockLevel" integer NOT NULL,
                    "ReorderThreshold" integer NOT NULL
                );
                CREATE TABLE IF NOT EXISTS "StockAlerts" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Sku" text NOT NULL,
                    "PackagingType" text NOT NULL,
                    "QuantityRequested" integer NOT NULL,
                    "Status" text NOT NULL,
                    "Timestamp" timestamp with time zone NOT NULL,
                    "WorkerId" text NOT NULL
                );
                CREATE TABLE IF NOT EXISTS "InventoryRolls" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "RawMaterialId" integer NOT NULL,
                    "BarcodeUrl" text NOT NULL,
                    "RollIdentifier" text NOT NULL,
                    "InitialQuantity" numeric NOT NULL,
                    "CurrentQuantity" numeric NOT NULL,
                    "Status" text NOT NULL,
                    "ReceivedDate" timestamp with time zone NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL
                );
                CREATE TABLE IF NOT EXISTS "StockLevels" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "RawMaterialId" integer NOT NULL,
                    "TotalQuantity" numeric NOT NULL,
                    "Notes" text NOT NULL,
                    "RecordedAt" timestamp with time zone NOT NULL
                );
                ALTER TABLE "InventoryItems" ADD COLUMN IF NOT EXISTS "PackagingTypeId" integer NULL;
                ALTER TABLE "InventoryItems" ADD COLUMN IF NOT EXISTS "RawMaterialId" integer NULL;
                ALTER TABLE "InventoryItems" ADD COLUMN IF NOT EXISTS "SkuNumber" integer NULL;
                ALTER TABLE "RawMaterials" ADD COLUMN IF NOT EXISTS "MaterialCode" character varying(20) NOT NULL DEFAULT '';
                ALTER TABLE "RawMaterials" ADD COLUMN IF NOT EXISTS "PackagingTypeId" integer NULL;
                """);

            // Existing rows use arbitrary user-entered category/SKU text. They
            // cannot be reliably mapped to the new hierarchy, so clear the old
            // development catalogue and its dependent order/stock records.
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF to_regclass('public."InventoryRolls"') IS NOT NULL THEN DELETE FROM "InventoryRolls"; END IF;
                    IF to_regclass('public."StockLevels"') IS NOT NULL THEN DELETE FROM "StockLevels"; END IF;
                    IF to_regclass('public."StockAlerts"') IS NOT NULL THEN DELETE FROM "StockAlerts"; END IF;
                    IF to_regclass('public."OrderLines"') IS NOT NULL THEN DELETE FROM "OrderLines"; END IF;
                    IF to_regclass('public."PurchaseOrders"') IS NOT NULL THEN DELETE FROM "PurchaseOrders"; END IF;
                    IF to_regclass('public."InventoryItems"') IS NOT NULL THEN DELETE FROM "InventoryItems"; END IF;
                    IF to_regclass('public."RawMaterials"') IS NOT NULL THEN DELETE FROM "RawMaterials"; END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                ALTER TABLE "RawMaterials" ALTER COLUMN "PackagingTypeId" SET NOT NULL;
                ALTER TABLE "RawMaterials" ALTER COLUMN "MaterialCode" DROP DEFAULT;
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_InventoryItems_Sku" ON "InventoryItems" ("Sku");
                CREATE INDEX IF NOT EXISTS "IX_RawMaterials_PackagingTypeId_MaterialCode" ON "RawMaterials" ("PackagingTypeId", "MaterialCode");
                CREATE INDEX IF NOT EXISTS "IX_InventoryRolls_RollIdentifier" ON "InventoryRolls" ("RollIdentifier");
                ALTER TABLE "RawMaterials" ADD CONSTRAINT "FK_RawMaterials_PackagingTypes_PackagingTypeId"
                    FOREIGN KEY ("PackagingTypeId") REFERENCES "PackagingTypes" ("Id") ON DELETE RESTRICT;
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""ALTER TABLE "RawMaterials" DROP CONSTRAINT IF EXISTS "FK_RawMaterials_PackagingTypes_PackagingTypeId";""");
            migrationBuilder.DropTable(name: "PackagingTypes");
        }
    }
}
