using ManufacturingCoordinator.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace ManufacturingCoordinator.Api.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20261003100000_AddInventoryIntegration")]
public class AddInventoryIntegration : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            ALTER TABLE "AgentWorkflows" ADD COLUMN "WorkflowType" text NOT NULL DEFAULT 'Procurement';
            ALTER TABLE "AgentWorkflows" ADD COLUMN "MachineId" uuid NULL;
            ALTER TABLE "AgentWorkflows" ADD COLUMN "PurchaseOrderId" integer NULL;
            ALTER TABLE "AgentWorkflows" ADD COLUMN "StateJson" text NULL;
            ALTER TABLE "InventoryRolls" ADD COLUMN IF NOT EXISTS "BatchId" text NULL;
            CREATE TABLE "InventoryMovements" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "RawMaterialId" integer NOT NULL, "RollIdentifier" text NOT NULL,
                "TransactionType" text NOT NULL, "Quantity" numeric NOT NULL,
                "PreviousStock" numeric NOT NULL, "NewStock" numeric NOT NULL,
                "Reason" text NOT NULL, "CreatedAt" timestamp with time zone NOT NULL);
            CREATE TABLE "GoodsReceipts" (
                "Id" uuid PRIMARY KEY, "PurchaseOrderId" integer NOT NULL REFERENCES "PurchaseOrders"("Id"),
                "OrderLineId" integer NOT NULL REFERENCES "OrderLines"("Id"),
                "ReceiptKey" text NOT NULL, "RollIdentifier" text NOT NULL, "BatchId" text NOT NULL,
                "Quantity" numeric NOT NULL, "ReceivedById" uuid NULL,
                "ReceivedAt" timestamp with time zone NOT NULL);
            CREATE UNIQUE INDEX "IX_GoodsReceipts_ReceiptKey" ON "GoodsReceipts"("ReceiptKey");
            CREATE TABLE "SupplierMaterialQuotes" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "SupplierId" integer NOT NULL REFERENCES "Suppliers"("Id"),
                "RawMaterialId" integer NOT NULL REFERENCES "RawMaterials"("Id"),
                "UnitPrice" numeric NOT NULL, "MinimumOrderQuantity" numeric NOT NULL,
                "PackSize" numeric NOT NULL, "AvailableQuantity" numeric NOT NULL,
                "LeadTimeDays" integer NOT NULL, "QualityEvidence" text NOT NULL,
                "Currency" text NOT NULL, "IsActive" boolean NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL);
            -- Backfill only exact identifier matches; retain unmatched historical QA rolls.
            UPDATE "InventoryRolls" i SET "BatchId" = q."BatchId"
            FROM "QualityInventoryRolls" q WHERE i."RollIdentifier" = q."Id" AND i."BatchId" IS NULL;
            """);
    }
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn("WorkflowType", "AgentWorkflows");
        migrationBuilder.DropColumn("MachineId", "AgentWorkflows");
        migrationBuilder.DropColumn("PurchaseOrderId", "AgentWorkflows");
        migrationBuilder.DropColumn("StateJson", "AgentWorkflows");
        migrationBuilder.DropTable("GoodsReceipts");
        migrationBuilder.DropTable("SupplierMaterialQuotes");
        migrationBuilder.DropTable("InventoryMovements");
        migrationBuilder.DropColumn("BatchId", "InventoryRolls");
    }
}
