using System;
using System.Text.Json.Serialization;

namespace backend.Models
{
    public class InventoryRoll
    {
        public string Id { get; set; } = string.Empty;
        
        // Foreign Key
        public int RawMaterialId { get; set; }
        
        public string? BatchId { get; set; } = "BATCH001";
        
        [JsonIgnore]
        public RawMaterial? RawMaterial { get; set; }
        
        // Generated by 3rd party QR service
        public string BarcodeUrl { get; set; } = string.Empty;
        public string RollIdentifier { get; set; } = string.Empty;
        
        public decimal InitialQuantity { get; set; }
        public decimal CurrentQuantity { get; set; }
        
        public string Status { get; set; } = "In Stock"; // In Stock, In Production, Depleted
        
        public DateTime ReceivedDate { get; set; } = DateTime.UtcNow;
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    }
}

