CREATE TABLE "InventoryItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Sku" text NOT NULL,
    "Name" text NOT NULL,
    "Category" text NOT NULL,
    "PackagingTypeId" integer,
    "RawMaterialId" integer,
    "SkuNumber" integer,
    "StockLevel" integer NOT NULL,
    "ReorderThreshold" integer NOT NULL,
    CONSTRAINT "PK_InventoryItems" PRIMARY KEY ("Id")
);


CREATE TABLE "InventoryMovements" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RawMaterialId" integer NOT NULL,
    "RollIdentifier" text NOT NULL,
    "TransactionType" text NOT NULL,
    "Quantity" numeric NOT NULL,
    "PreviousStock" numeric NOT NULL,
    "NewStock" numeric NOT NULL,
    "Reason" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InventoryMovements" PRIMARY KEY ("Id")
);


CREATE TABLE "PackagingTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "ShortCode" character varying(12) NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_PackagingTypes" PRIMARY KEY ("Id")
);


CREATE TABLE "StockAlerts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Sku" text NOT NULL,
    "PackagingType" text NOT NULL,
    "QuantityRequested" integer NOT NULL,
    "Status" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "WorkerId" text NOT NULL,
    "MaterialId" integer,
    "MaterialName" character varying(200),
    "CurrentStock" numeric NOT NULL,
    "RequiredQuantity" numeric NOT NULL,
    "SafetyStock" numeric NOT NULL,
    "OpenPurchaseQuantity" numeric NOT NULL,
    "NetDeficit" numeric NOT NULL,
    "Severity" character varying(50) NOT NULL,
    "IsRead" boolean NOT NULL,
    CONSTRAINT "PK_StockAlerts" PRIMARY KEY ("Id")
);


CREATE TABLE "RawMaterials" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SkuCode" character varying(255) NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Category" text NOT NULL,
    "MaterialCode" character varying(20) NOT NULL,
    "PackagingTypeId" integer NOT NULL,
    "UnitOfMeasure" text NOT NULL,
    "ReorderThreshold" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RawMaterials" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RawMaterials_PackagingTypes_PackagingTypeId" FOREIGN KEY ("PackagingTypeId") REFERENCES "PackagingTypes" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "InventoryRolls" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RawMaterialId" integer NOT NULL,
    "BatchId" text,
    "BarcodeUrl" text NOT NULL,
    "RollIdentifier" text NOT NULL,
    "InitialQuantity" numeric NOT NULL,
    "CurrentQuantity" numeric NOT NULL,
    "Status" text NOT NULL,
    "ReceivedDate" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InventoryRolls" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InventoryRolls_RawMaterials_RawMaterialId" FOREIGN KEY ("RawMaterialId") REFERENCES "RawMaterials" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "StockLevels" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RawMaterialId" integer NOT NULL,
    "TotalQuantity" numeric NOT NULL,
    "Notes" text NOT NULL,
    "RecordedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StockLevels" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StockLevels_RawMaterials_RawMaterialId" FOREIGN KEY ("RawMaterialId") REFERENCES "RawMaterials" ("Id") ON DELETE CASCADE
);


CREATE UNIQUE INDEX "IX_InventoryItems_Sku" ON "InventoryItems" ("Sku");


CREATE INDEX "IX_InventoryRolls_RawMaterialId" ON "InventoryRolls" ("RawMaterialId");


CREATE UNIQUE INDEX "IX_InventoryRolls_RollIdentifier" ON "InventoryRolls" ("RollIdentifier");


CREATE UNIQUE INDEX "IX_PackagingTypes_Name" ON "PackagingTypes" ("Name");


CREATE UNIQUE INDEX "IX_PackagingTypes_ShortCode" ON "PackagingTypes" ("ShortCode");


CREATE INDEX "IX_RawMaterials_PackagingTypeId_MaterialCode" ON "RawMaterials" ("PackagingTypeId", "MaterialCode");


CREATE UNIQUE INDEX "IX_RawMaterials_SkuCode" ON "RawMaterials" ("SkuCode");


CREATE INDEX "IX_StockLevels_RawMaterialId" ON "StockLevels" ("RawMaterialId");


