START TRANSACTION;

ALTER TABLE "InventoryRoll" DROP CONSTRAINT "FK_InventoryRoll_RawMaterials_RawMaterialId";

ALTER TABLE "StockLevel" DROP CONSTRAINT "FK_StockLevel_RawMaterials_RawMaterialId";

ALTER TABLE "StockLevel" DROP CONSTRAINT "PK_StockLevel";

ALTER TABLE "InventoryRoll" DROP CONSTRAINT "PK_InventoryRoll";

ALTER TABLE "StockLevel" RENAME TO "StockLevels";

ALTER TABLE "InventoryRoll" RENAME TO "InventoryRolls";

ALTER INDEX "IX_StockLevel_RawMaterialId" RENAME TO "IX_StockLevels_RawMaterialId";

ALTER INDEX "IX_InventoryRoll_RawMaterialId" RENAME TO "IX_InventoryRolls_RawMaterialId";

ALTER TABLE "PurchaseOrders" ADD "ActualDeliveryDate" timestamp with time zone;

ALTER TABLE "PurchaseOrders" ADD "BankReferenceNumber" character varying(100);

ALTER TABLE "PurchaseOrders" ADD "BankSlipStatus" character varying(50);

ALTER TABLE "PurchaseOrders" ADD "BankSlipUploadedAt" timestamp with time zone;

ALTER TABLE "PurchaseOrders" ADD "BankSlipUrl" character varying(500);

ALTER TABLE "PurchaseOrders" ADD "DeliveryRemarks" character varying(500);

ALTER TABLE "PurchaseOrders" ADD "ExpectedDeliveryDate" timestamp with time zone;

ALTER TABLE "PurchaseOrders" ADD "IsAcknowledgedByScm" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "PurchaseOrders" ADD "IsFinancialVerified" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "PurchaseOrders" ADD "IsQualityVerified" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "PurchaseOrders" ADD "ProcurementRequestId" integer;

ALTER TABLE "PurchaseOrders" ADD "TrackingNumber" character varying(200);

ALTER TABLE "PurchaseOrders" ADD "TrackingStatus" character varying(50) NOT NULL DEFAULT 'Draft';

ALTER TABLE "AgentWorkflows" ADD "MachineId" uuid;

ALTER TABLE "AgentWorkflows" ADD "PurchaseOrderId" integer;

ALTER TABLE "AgentWorkflows" ADD "StateJson" text;

ALTER TABLE "AgentWorkflows" ADD "ValidationResults" text;

ALTER TABLE "AgentWorkflows" ADD "WorkflowType" text NOT NULL DEFAULT '';

ALTER TABLE "InventoryRolls" ADD "BatchId" text;

ALTER TABLE "StockLevels" ADD CONSTRAINT "PK_StockLevels" PRIMARY KEY ("Id");

ALTER TABLE "InventoryRolls" ADD CONSTRAINT "PK_InventoryRolls" PRIMARY KEY ("Id");

CREATE TABLE "GoodsReceipts" (
    "Id" uuid NOT NULL,
    "PurchaseOrderId" integer NOT NULL,
    "OrderLineId" integer NOT NULL,
    "ReceiptKey" text NOT NULL,
    "RollIdentifier" text NOT NULL,
    "BatchId" text NOT NULL,
    "Quantity" numeric NOT NULL,
    "ReceivedById" uuid,
    "ReceivedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GoodsReceipts" PRIMARY KEY ("Id")
);

CREATE TABLE "InventoryItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Sku" text NOT NULL,
    "Name" text NOT NULL,
    "Category" text NOT NULL,
    "PackagingTypeId" integer,
    "RawMaterialId" integer,
    "SkuNumber" integer,
    "StockLevel" integer NOT NULL,
    "ReorderThreshold" integer NOT NULL,
    CONSTRAINT "PK_InventoryItems" PRIMARY KEY ("Id")
);

CREATE TABLE "InventoryMovements" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RawMaterialId" integer NOT NULL,
    "RollIdentifier" text NOT NULL,
    "TransactionType" text NOT NULL,
    "Quantity" numeric NOT NULL,
    "PreviousStock" numeric NOT NULL,
    "NewStock" numeric NOT NULL,
    "Reason" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InventoryMovements" PRIMARY KEY ("Id")
);

CREATE TABLE "ProcurementOutcomes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Material" character varying(200) NOT NULL,
    "RequestedQuantity" numeric(18,3) NOT NULL,
    "RecommendedQuantity" numeric(18,3) NOT NULL,
    "FinalOrderedQuantity" numeric(18,3) NOT NULL,
    "RecommendedSupplier" character varying(200) NOT NULL,
    "SelectedSupplier" character varying(200) NOT NULL,
    "EstimatedPrice" numeric(18,2) NOT NULL,
    "FinalPrice" numeric(18,2) NOT NULL,
    "EstimatedLeadTime" integer NOT NULL,
    "ActualLeadTime" integer NOT NULL,
    "QualityEvidence" character varying(1000) NOT NULL,
    "SupplierVerification" character varying(100) NOT NULL,
    "ManagerDecision" character varying(100) NOT NULL,
    "ManagerRevision" character varying(1000),
    "ProcurementSuccess" boolean NOT NULL,
    "PaymentSuccess" boolean NOT NULL,
    "DeliverySuccess" boolean NOT NULL,
    "QualityOutcome" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "CompletedAt" timestamp with time zone,
    "PurchaseOrderId" integer,
    "ProcurementRequestId" integer,
    CONSTRAINT "PK_ProcurementOutcomes" PRIMARY KEY ("Id")
);

CREATE TABLE "ProcurementRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RawMaterialId" integer NOT NULL,
    "RequiredSpecification" character varying(200) NOT NULL,
    "ProductionRequirement" numeric(18,3) NOT NULL,
    "CurrentStock" numeric(18,3) NOT NULL,
    "SafetyStock" numeric(18,3) NOT NULL,
    "ExistingOpenPoQuantity" numeric(18,3) NOT NULL,
    "CalculatedNetQuantity" numeric(18,3) NOT NULL,
    "MaximumBudget" numeric(18,2) NOT NULL,
    "RequiredByDate" timestamp with time zone NOT NULL,
    "QualityRequirement" character varying(500) NOT NULL,
    "PreferredRegion" character varying(100),
    "Status" text NOT NULL,
    "WorkflowId" character varying(100),
    "MaterialName" character varying(200),
    "RecommendedSupplierId" integer,
    "GeneratedPurchaseOrderId" integer,
    "FailureReason" character varying(1000),
    "CreatedById" uuid,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "Priority" character varying(50) NOT NULL,
    CONSTRAINT "PK_ProcurementRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProcurementRequests_PurchaseOrders_GeneratedPurchaseOrderId" FOREIGN KEY ("GeneratedPurchaseOrderId") REFERENCES "PurchaseOrders" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_ProcurementRequests_RawMaterials_RawMaterialId" FOREIGN KEY ("RawMaterialId") REFERENCES "RawMaterials" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ProcurementRequests_Suppliers_RecommendedSupplierId" FOREIGN KEY ("RecommendedSupplierId") REFERENCES "Suppliers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_ProcurementRequests_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE TABLE "StockAlerts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Sku" text NOT NULL,
    "PackagingType" text NOT NULL,
    "QuantityRequested" integer NOT NULL,
    "Status" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "WorkerId" text NOT NULL,
    "MaterialId" integer,
    "MaterialName" character varying(200),
    "CurrentStock" numeric NOT NULL,
    "RequiredQuantity" numeric NOT NULL,
    "SafetyStock" numeric NOT NULL,
    "OpenPurchaseQuantity" numeric NOT NULL,
    "NetDeficit" numeric NOT NULL,
    "Severity" character varying(50) NOT NULL,
    "IsRead" boolean NOT NULL,
    CONSTRAINT "PK_StockAlerts" PRIMARY KEY ("Id")
);

CREATE TABLE "SupplierMaterialQuotes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SupplierId" integer NOT NULL,
    "RawMaterialId" integer NOT NULL,
    "UnitPrice" numeric NOT NULL,
    "MinimumOrderQuantity" numeric NOT NULL,
    "PackSize" numeric NOT NULL,
    "AvailableQuantity" numeric NOT NULL,
    "LeadTimeDays" integer NOT NULL,
    "QualityEvidence" character varying(500) NOT NULL,
    "Currency" character varying(10) NOT NULL,
    "IsActive" boolean NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SupplierMaterialQuotes" PRIMARY KEY ("Id")
);

CREATE TABLE "SupplierCandidates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProcurementRequestId" integer NOT NULL,
    "SupplierId" integer,
    "SupplierName" character varying(200) NOT NULL,
    "MaterialName" character varying(200) NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "Currency" character varying(10) NOT NULL DEFAULT 'USD',
    "MinimumOrderQuantity" numeric(18,3) NOT NULL,
    "PackSize" numeric(18,3) NOT NULL DEFAULT 1.0,
    "LeadTimeDays" integer NOT NULL,
    "QualityEvidence" character varying(500) NOT NULL,
    "Availability" character varying(100) NOT NULL DEFAULT 'In Stock',
    "SupplierStatus" character varying(50) NOT NULL DEFAULT 'UNVERIFIED',
    "ConfidenceScore" numeric(5,2) NOT NULL,
    "SourceUrl" character varying(500),
    "IsValidated" boolean NOT NULL,
    "ValidationRemarks" character varying(1000),
    "RecommendedOrderQuantity" numeric(18,3) NOT NULL,
    "TotalCost" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_SupplierCandidates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SupplierCandidates_ProcurementRequests_ProcurementRequestId" FOREIGN KEY ("ProcurementRequestId") REFERENCES "ProcurementRequests" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SupplierCandidates_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX "IX_InventoryRolls_RollIdentifier" ON "InventoryRolls" ("RollIdentifier");

CREATE UNIQUE INDEX "IX_GoodsReceipts_ReceiptKey" ON "GoodsReceipts" ("ReceiptKey");

CREATE UNIQUE INDEX "IX_InventoryItems_Sku" ON "InventoryItems" ("Sku");

CREATE INDEX "IX_ProcurementRequests_CreatedById" ON "ProcurementRequests" ("CreatedById");

CREATE INDEX "IX_ProcurementRequests_GeneratedPurchaseOrderId" ON "ProcurementRequests" ("GeneratedPurchaseOrderId");

CREATE INDEX "IX_ProcurementRequests_RawMaterialId" ON "ProcurementRequests" ("RawMaterialId");

CREATE INDEX "IX_ProcurementRequests_RecommendedSupplierId" ON "ProcurementRequests" ("RecommendedSupplierId");

CREATE INDEX "IX_SupplierCandidates_ProcurementRequestId" ON "SupplierCandidates" ("ProcurementRequestId");

CREATE INDEX "IX_SupplierCandidates_SupplierId" ON "SupplierCandidates" ("SupplierId");

ALTER TABLE "InventoryRolls" ADD CONSTRAINT "FK_InventoryRolls_RawMaterials_RawMaterialId" FOREIGN KEY ("RawMaterialId") REFERENCES "RawMaterials" ("Id") ON DELETE RESTRICT;

ALTER TABLE "StockLevels" ADD CONSTRAINT "FK_StockLevels_RawMaterials_RawMaterialId" FOREIGN KEY ("RawMaterialId") REFERENCES "RawMaterials" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261003164543_IntegrationModelAlignment', '8.0.11');

COMMIT;

